### ISSUE TITLE
SVL bootloader fails to erase upper half of flash

### ISSUE THREAD

**Issue by jkovachnet** [sparkfun/Apollo3_Uploader_SVL#8]
The SVL bootloader code (the firmware that runs on the Artemis, not the scripts that run on the PC side) contains a logic error that causes issues when programming large flash images.

The flash on the Apollo3 chip is divided into two instances, each of which is divided into 64 pages. Instance 0's pages are numbered 0-63, and instance 1's pages are also numbered 0-63. The bootloader code keeps track of the flash page number when erasing flash during programming. However, it doesn't handle the page number rolling over to 0 once the upper flash instance is reached. As a result, it will never erase any pages in the upper flash instance. This causes erratic behavior once the application size exceeds ~450K or so - the board will program and run fine on the first attempt, but will hang after all subsequent programming attempts as the upper half of flash gets corrupted (due to the failure to erase before reprogramming).

**Comment by nseidle** [comment]
Thanks for reporting! I'm just starting to dig in.

We are erasing the correct instance [here](https://github.com/sparkfun/Apollo3_Uploader_SVL/blob/main/bootloader/src/main.c#L597). It's not yet clear if we are [writing](https://github.com/sparkfun/Apollo3_Uploader_SVL/blob/main/bootloader/src/main.c#L608) to the correct instance.

**Comment by jkovachnet** [comment]
The issue is the check on line 592... it needs to check the instance number as well as the page number. Once the instance rolls over to 1, the page number goes back to 0. But *p_last_page_erased is 63 because the last page we erased was page 63 in instance 0. So the check fails (63 > 0) and we never make it to line 597 (where the flash is actually erased).

Apologies for the delay in responding. I've implemented a local workaround... I'd send a patch, but I can't because (reasons).

**Comment by nseidle** [comment]
> I'd send a patch, but I can't because (reasons).

Hah! No problem. I can imagine.

> The issue is the check on line 592... 

Perfect, thank you. I'm stuck getting our makefile to work on my system. I'm thankful you have a workaround for the time being. I hope to get a fix in soon.

**Comment by dboddie** [comment]
It looks like I just ran into this issue. My payload looks fine in flash all the way up to 0x80000 then null bytes after that.

**Comment by gigapod** [comment]
This https://github.com/sparkfun/Apollo3_Uploader_SVL/pull/10 fixes this issue. I just got the GH Action build for this system working again ( with macOS included) and a few more cleanup things.
